export const ERROR_CODES = {
  // Auth errors
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  PHONE_ALREADY_EXISTS: 'PHONE_ALREADY_EXISTS',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_BANNED: 'ACCOUNT_BANNED',

  // User errors
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_PASSWORD: 'INVALID_PASSWORD',

  // Resource errors
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  SUBSCRIPTION_NOT_FOUND: 'SUBSCRIPTION_NOT_FOUND',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  PROPOSAL_NOT_FOUND: 'PROPOSAL_NOT_FOUND',
  REVIEW_NOT_FOUND: 'REVIEW_NOT_FOUND',
  TICKET_NOT_FOUND: 'TICKET_NOT_FOUND',

  // Permission errors
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',

  // Validation errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',

  // Business logic errors
  ORDER_ALREADY_CANCELLED: 'ORDER_ALREADY_CANCELLED',
  ORDER_CANNOT_BE_CANCELLED: 'ORDER_CANNOT_BE_CANCELLED',
  REVIEW_ALREADY_EXISTS: 'REVIEW_ALREADY_EXISTS',
  REVIEW_EDIT_WINDOW_EXPIRED: 'REVIEW_EDIT_WINDOW_EXPIRED',
  QR_CODE_INVALID: 'QR_CODE_INVALID',
  QR_CODE_ALREADY_USED: 'QR_CODE_ALREADY_USED',
  MAX_REGENERATIONS_REACHED: 'MAX_REGENERATIONS_REACHED',

  // Payment errors
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_ALREADY_PROCESSED: 'PAYMENT_ALREADY_PROCESSED',
  REFUND_FAILED: 'REFUND_FAILED',

  // Rate limiting
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',

  // Server errors
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
};

export const ERROR_MESSAGES = {
  // Auth
  [ERROR_CODES.INVALID_CREDENTIALS]: 'Email ou mot de passe incorrect',
  [ERROR_CODES.EMAIL_ALREADY_EXISTS]: 'Cet email est déjà utilisé',
  [ERROR_CODES.PHONE_ALREADY_EXISTS]: 'Ce numéro de téléphone est déjà utilisé',
  [ERROR_CODES.INVALID_TOKEN]: 'Token invalide',
  [ERROR_CODES.TOKEN_EXPIRED]: 'Token expiré',
  [ERROR_CODES.EMAIL_NOT_VERIFIED]: 'Email non vérifié',
  [ERROR_CODES.ACCOUNT_SUSPENDED]: 'Compte suspendu',
  [ERROR_CODES.ACCOUNT_BANNED]: 'Compte banni',

  // User
  [ERROR_CODES.USER_NOT_FOUND]: 'Utilisateur introuvable',
  [ERROR_CODES.INVALID_PASSWORD]: 'Mot de passe incorrect',

  // Resources
  [ERROR_CODES.RESOURCE_NOT_FOUND]: 'Ressource introuvable',
  [ERROR_CODES.SUBSCRIPTION_NOT_FOUND]: 'Abonnement introuvable',
  [ERROR_CODES.ORDER_NOT_FOUND]: 'Commande introuvable',
  [ERROR_CODES.PROPOSAL_NOT_FOUND]: 'Proposition introuvable',
  [ERROR_CODES.REVIEW_NOT_FOUND]: 'Avis introuvable',
  [ERROR_CODES.TICKET_NOT_FOUND]: 'Ticket introuvable',

  // Permissions
  [ERROR_CODES.UNAUTHORIZED]: 'Non authentifié',
  [ERROR_CODES.FORBIDDEN]: 'Accès refusé',
  [ERROR_CODES.INSUFFICIENT_PERMISSIONS]: 'Permissions insuffisantes',

  // Validation
  [ERROR_CODES.VALIDATION_ERROR]: 'Erreur de validation',
  [ERROR_CODES.INVALID_INPUT]: 'Données invalides',

  // Business logic
  [ERROR_CODES.ORDER_ALREADY_CANCELLED]: 'Commande déjà annulée',
  [ERROR_CODES.ORDER_CANNOT_BE_CANCELLED]: 'Cette commande ne peut plus être annulée',
  [ERROR_CODES.REVIEW_ALREADY_EXISTS]: 'Vous avez déjà laissé un avis pour cette commande',
  [ERROR_CODES.REVIEW_EDIT_WINDOW_EXPIRED]: 'Délai de modification dépassé',
  [ERROR_CODES.QR_CODE_INVALID]: 'QR code invalide',
  [ERROR_CODES.QR_CODE_ALREADY_USED]: 'QR code déjà utilisé',
  [ERROR_CODES.MAX_REGENERATIONS_REACHED]: 'Nombre maximum de régénérations atteint',

  // Payment
  [ERROR_CODES.PAYMENT_FAILED]: 'Échec du paiement',
  [ERROR_CODES.PAYMENT_ALREADY_PROCESSED]: 'Paiement déjà traité',
  [ERROR_CODES.REFUND_FAILED]: 'Échec du remboursement',

  // Rate limiting
  [ERROR_CODES.TOO_MANY_REQUESTS]: 'Trop de requêtes, veuillez réessayer plus tard',

  // Server
  [ERROR_CODES.INTERNAL_SERVER_ERROR]: 'Erreur serveur interne',
  [ERROR_CODES.DATABASE_ERROR]: 'Erreur de base de données',
  [ERROR_CODES.EXTERNAL_SERVICE_ERROR]: 'Erreur de service externe',
};